In [ ]:
from sklearn.datasets import make_classification

In [ ]:
X, Y = make_classification(n_samples = 100, n_features = 4, random_state = 11)

In [ ]:
X

array([[-1.0487505 ,  0.41116419,  1.67929229,  0.6328284 ],
       [ 0.44050753, -0.18488778, -0.67517802, -0.2832823 ],
       [-0.73911397,  0.15889491,  1.5075798 ,  0.25831477],
       [ 0.54953284, -0.89060719,  0.79197156, -1.29977368],
       [-0.11329626, -0.42368439,  1.34057342, -0.60289224],
       [-0.04930961, -0.54514716,  1.47677321, -0.77970628],
       [-0.65288789,  1.10044686, -1.04576056,  1.60494221],
       [ 1.112402  , -0.77666579, -0.93791814, -1.15957914],
       [ 0.29494586,  0.11017406, -1.03144404,  0.14583382],
       [-0.1817526 ,  0.8210916 , -1.56578581,  1.18493177],
       [-0.88367978,  0.48842882,  1.06338928,  0.73682263],
       [ 0.90289808, -0.46393696, -1.17346914, -0.70249345],
       [ 0.13678268,  0.17127478, -0.7759412 ,  0.23997015],
       [ 0.05526192, -0.42440204,  0.90880762, -0.61086794],
       [-0.92860899,  0.93778112,  0.06622104,  1.38304329],
       [ 1.49730823, -1.1065755 , -1.1109687 , -1.64853076],
       [ 0.60224524, -0.36710731, -0.63994877, -0.55124974],
       [-1.17155464,  0.74853439,  1.15972437,  1.12167663],
       [-0.08152128, -0.34053749,  1.05294974, -0.48496949],
       [-0.31237891, -0.31798364,  1.59088098, -0.44311331],
       [-0.70183398,  1.14140543, -1.02129347,  1.66569377],
       [-0.73875608,  0.72986104,  0.09277827,  1.07706271],
       [-0.27206755,  0.54544384, -0.65090433,  0.79337625],
       [-1.08817472,  0.19287117,  2.32125212,  0.321422  ],
       [ 0.61826912, -0.27945843, -0.8982078 , -0.42622205],
       [-1.31898373,  0.71427716,  1.62375289,  1.07862774],
       [-0.14407416,  0.79551451, -1.59936084,  1.14670155],
       [-0.29033393, -0.54262497,  2.09045822, -0.76615642],
       [ 1.09756556, -0.7188097 , -1.04302663, -1.07600233],
       [ 1.01889115, -0.61051013, -1.10885256, -0.91745895],
       [-0.55859644,  0.94642463, -0.90687988,  1.38018916],
       [-0.78580427,  1.11708578, -0.74509364,  1.63428007],
       [ 0.3250291 ,  0.26617011, -1.49511251,  0.36829163],
       [-0.13922611,  0.69853525, -1.37168101,  1.00743396],
       [-0.70592719, -0.12471272,  2.12451755, -0.1497449 ],
       [ 0.34639287,  0.48647473, -2.09560095,  0.68332695],
       [-0.05662351,  0.66613631, -1.50391108,  0.95756983],
       [ 0.78381608, -0.44066504, -0.9248104 , -0.66421405],
       [-0.33595877,  0.63733188, -0.71411379,  0.92777633],
       [-0.55060971,  0.75059009, -0.44247806,  1.09903422],
       [ 0.16048561, -0.58590667,  1.0380985 , -0.84680126],
       [ 0.45995206, -0.84118347,  0.8999916 , -1.22520853],
       [-0.2272574 , -0.63221365,  2.15006923, -0.89722565],
       [ 0.9247812 , -0.56094076, -0.98954388, -0.84249827],
       [ 1.24780525, -0.83674218, -1.13741744, -1.25130861],
       [ 0.94247762, -0.61901894, -0.8912415 , -0.92651142],
       [ 0.57929973, -0.89276047,  0.72074132, -1.30408823],
       [ 0.88890709, -0.52734907, -0.98045625, -0.79284951],
       [-0.97945126,  1.19726256, -0.44556205,  1.75723374],
       [ 0.85160315, -0.49476606, -0.96519317, -0.74458827],
       [-0.45695469,  0.03267204,  1.09441238,  0.06568349],
       [ 1.03881594, -0.67881542, -0.99095633, -1.01622956],
       [ 0.55849365, -0.2589536 , -0.79523733, -0.39435477],
       [ 0.72118719, -1.05786407,  0.76464261, -1.54669344],
       [-1.10922143,  0.69677773,  1.12756397,  1.04488896],
       [-1.38677264,  0.88838115,  1.36697752,  1.33108573],
       [-0.25332482,  0.74249324, -1.18706448,  1.07517172],
       [-1.64237971,  0.73905365,  2.39419505,  1.12748485],
       [-0.25476649,  0.54737977, -0.70019774,  0.79543936],
       [-1.54549419,  1.80023423, -0.48279796,  2.64521988],
       [ 0.85753926, -0.44215299, -1.11074675, -0.66938602],
       [-1.13913431,  0.3357373 ,  2.0985448 ,  0.52839147],
       [ 0.17196476, -0.59719083,  1.03651627, -0.86345577],
       [-0.87110236,  0.35461681,  1.36239745,  0.54441852],
       [ 1.54565992, -1.25252901, -0.87390843, -1.85982005],
       [-0.36925516,  0.56410643, -0.4471454 ,  0.8241436 ],
       [-0.12627142,  0.58277687, -1.11834935,  0.84090311],
       [-0.76991956,  0.44380354,  0.88129578,  0.66814193],
       [ 0.01653536,  0.74807074, -1.89497445,  1.0720484 ],
       [ 0.54111123, -0.87926888,  0.78555552, -1.28316753],
       [ 0.05541297,  0.4259098 , -1.19720451,  0.60846894],
       [ 1.47224273, -1.10586846, -1.04824941, -1.64648387],
       [-1.37960181,  0.57834403,  2.11627727,  0.88619847],
       [-1.65843364,  1.57000206,  0.37781282,  2.3197225 ],
       [ 0.06991019, -0.57200542,  1.23664091, -0.82313416],
       [-0.1746952 ,  0.7311935 , -1.36132361,  1.05572748],
       [-1.08640615,  0.83139867,  0.7355203 ,  1.23699448],
       [-0.46231954,  0.61927583, -0.34439334,  0.9070916 ],
       [-0.70333167,  1.28495347, -1.37290872,  1.87160269],
       [ 0.0075425 , -0.59615562,  1.45685782, -0.85519514],
       [ 0.91458127, -0.56079467, -0.96367075, -0.84186842],
       [ 0.71433585, -0.43543348, -0.75905751, -0.6538486 ],
       [-1.36551245,  1.04050603,  0.93558871,  1.54835591],
       [ 0.34809631, -0.76187752,  0.99130707, -1.10687439],
       [ 1.03351849, -1.20802752,  0.33315473, -1.77489884],
       [-1.61231421,  1.11598973,  1.38345937,  1.66677032],
       [-0.68767547, -0.16107301,  2.16761172, -0.20263757],
       [ 1.47967819, -1.11320288, -1.04921173, -1.65730782],
       [-0.54214192, -0.27371653,  2.07222837, -0.37016553],
       [-0.49261826, -0.54552346,  2.61792455, -0.76197633],
       [ 0.47782701, -0.81554563,  0.79052915, -1.18918064],
       [-0.18021278,  0.64821443, -1.14165132,  0.93696328],
       [ 0.84151193, -0.92385053,  0.12330218, -1.35947747],
       [ 0.3700698 , -0.79596996,  1.01921277, -1.15666836],
       [-1.13074458,  0.96845076,  0.51018017,  1.43535379],
       [-0.2940586 , -0.57950137,  2.19135519, -0.8188835 ],
       [ 0.65793207, -0.36542645, -0.78734133, -0.55113436],
       [-1.03512956,  0.51136127,  1.39614074,  0.77594918],
       [ 1.79813343, -1.28539361, -1.44190473, -1.91735262],
       [ 1.03518524, -0.68211788, -0.97344007, -1.02081564]])

In [ ]:
Y

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(columns = ['x1', 'x2', 'x3', 'x4'], data = X[0:, 0:])
df

          x1        x2        x3        x4
0  -1.048751  0.411164  1.679292  0.632828
1   0.440508 -0.184888 -0.675178 -0.283282
2  -0.739114  0.158895  1.507580  0.258315
3   0.549533 -0.890607  0.791972 -1.299774
4  -0.113296 -0.423684  1.340573 -0.602892
..       ...       ...       ...       ...
95 -0.294059 -0.579501  2.191355 -0.818883
96  0.657932 -0.365426 -0.787341 -0.551134
97 -1.035130  0.511361  1.396141  0.775949
98  1.798133 -1.285394 -1.441905 -1.917353
99  1.035185 -0.682118 -0.973440 -1.020816

[100 rows x 4 columns]

In [ ]:
df['Y'] = Y
df

          x1        x2        x3        x4  Y
0  -1.048751  0.411164  1.679292  0.632828  1
1   0.440508 -0.184888 -0.675178 -0.283282  0
2  -0.739114  0.158895  1.507580  0.258315  1
3   0.549533 -0.890607  0.791972 -1.299774  0
4  -0.113296 -0.423684  1.340573 -0.602892  0
..       ...       ...       ...       ... ..
95 -0.294059 -0.579501  2.191355 -0.818883  0
96  0.657932 -0.365426 -0.787341 -0.551134  0
97 -1.035130  0.511361  1.396141  0.775949  1
98  1.798133 -1.285394 -1.441905 -1.917353  0
99  1.035185 -0.682118 -0.973440 -1.020816  0

[100 rows x 5 columns]

In [ ]:
import numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))

class LogisticRegression():

    def __init__(self, lr=0.001, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            linear_pred = np.dot(X, self.weights) + self.bias
            predictions = sigmoid(linear_pred)

            dw = (1/n_samples) * np.dot(X.T, (predictions - y))
            db = (1/n_samples) * np.sum(predictions-y)

            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db


    def predict(self, X):
        linear_pred = np.dot(X, self.weights) + self.bias
        y_pred = sigmoid(linear_pred)
        class_pred = [0 if y<=0.5 else 1 for y in y_pred]
        return class_pred

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop(columns = 'Y')
Y = df['Y']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 11)

In [ ]:
clf = LogisticRegression(lr=0.01)
clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)
Y_pred

[0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0]

In [ ]:
def accuracy(y_pred, y_test):
    return np.sum(y_pred==y_test)/len(y_test)

In [ ]:
print('Accuracy =', accuracy(Y_pred, Y_test))

Accuracy = 0.95